


DROP TABLE IF EXISTS MST_DICT;
CREATE TABLE MST_DICT (
  ID		INT 	NOT NULL AUTO_INCREMENT	COMMENT '主键',
  CODE  	VARCHAR(64) 	NOT NULL		COMMENT '参数码值',
  NAME  	VARCHAR(64)		NOT NULL		COMMENT '参数名称',
  STATUS  	VARCHAR(64)		NOT NULL		COMMENT '参数状态',
  PRIMARY KEY (ID)
);
INSERT INTO MST_DICT (CODE,NAME,STATUS) VALUES('CHN','中国','1'),('US','美国','1'),('ENG','英国','1');